-- ================================================================================
--              Oracle 통합 테이블 생성 스크립트 (최종 정리본)
--              ※ regDate 추가 완료
--              ※ 출석은 kanji_log 기반 판단
-- ================================================================================


-- ================================================================================
-- 0. 기존 테이블 삭제 (의존성 역순)
-- ================================================================================
DROP TABLE kanji_log PURGE;
DROP TABLE kanji PURGE;
DROP TABLE account PURGE;


-- ================================================================================
-- 1. 회원 테이블 (account)
-- ================================================================================
-- accID     : 내부 PK (자동생성)
-- userID    : 로그인 ID (이메일, UNIQUE)
-- regDate   : 가입일 (자동생성, 캘린더 가입일 이전 회색 처리용)
-- attendance: 컬럼은 존재하지만 실제 출석은 kanji_log 기반
-- ================================================================================

CREATE TABLE account (
    accID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID      VARCHAR2(50)  NOT NULL UNIQUE,
    userPW1     VARCHAR2(100) NOT NULL,
    userPW2     VARCHAR2(100) NOT NULL,
    email       VARCHAR2(100) NOT NULL,
    phone       VARCHAR2(20),
    attendance  VARCHAR2(50),
    nickname    VARCHAR2(50)  NOT NULL,
    regDate     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);


-- ================================================================================
-- 2. 한자 테이블 (kanji)
-- ================================================================================

CREATE TABLE kanji (
    kanjiID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kanjiindex          VARCHAR2(20)  NOT NULL UNIQUE,
    kanji               NCHAR(1)      NOT NULL,
    onyomi1             VARCHAR2(10),
    onyomi2             VARCHAR2(10),
    onyomi3             VARCHAR2(10),
    kunyomi1            VARCHAR2(30),
    kunyomi2            VARCHAR2(30),
    kunyomi3            VARCHAR2(30),
    korean_meaning      VARCHAR2(20)  NOT NULL,
    meaning_description VARCHAR2(100),
    example1            VARCHAR2(100),
    example2            VARCHAR2(100),
    example3            VARCHAR2(100),
    jlpt_level          VARCHAR2(2)   NOT NULL,
    sector              NUMBER        NOT NULL,
    index_num           NUMBER        NOT NULL,
    created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT ck_kanji_jlpt CHECK (jlpt_level IN ('N5','N4','N3','N2','N1'))
);

-- 인덱스
CREATE INDEX idx_kanji_jlpt   ON kanji (jlpt_level);
CREATE INDEX idx_kanji_sector ON kanji (jlpt_level, sector);
CREATE INDEX idx_kanji_char   ON kanji (kanji);

-- 수정일 자동 갱신 트리거
CREATE OR REPLACE TRIGGER trg_kanji_updated_at
BEFORE UPDATE ON kanji
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/


-- ================================================================================
-- 3. 학습 로그 테이블 (kanji_log) — 출석 판단 겸용
-- ================================================================================
-- ★ 출석 기준: 해당 날짜에 kanji_log row 1개 이상 → 출석 O
-- ★ 별도 attendance 테이블 없음
-- ================================================================================

CREATE TABLE kanji_log (
    logID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    accID       NUMBER       NOT NULL,
    kanjiID     NUMBER       NOT NULL,
    is_correct  NUMBER(1)    NOT NULL CHECK (is_correct IN (0, 1)),
    jlpt_level  VARCHAR2(2),
    sector      NUMBER,
    studied_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_klog_account FOREIGN KEY (accID)
        REFERENCES account(accID) ON DELETE CASCADE,
    CONSTRAINT fk_klog_kanji FOREIGN KEY (kanjiID)
        REFERENCES kanji(kanjiID) ON DELETE CASCADE
);

CREATE INDEX idx_log_acc_date ON kanji_log (accID, TRUNC(studied_at));
CREATE INDEX idx_log_acc ON kanji_log (accID);
CREATE INDEX idx_log_level ON kanji_log (accID, jlpt_level);

COMMIT;

-- ★ 기존 DB에 컬럼 추가 시 (ALTER TABLE):
-- ALTER TABLE kanji_log ADD jlpt_level VARCHAR2(2);
-- ALTER TABLE kanji_log ADD sector NUMBER;
-- CREATE INDEX idx_log_level ON kanji_log (accID, jlpt_level);


-- ================================================================================
-- 4. N5 샘플 데이터 INSERT (섹터 1~4, 총 40개)
-- ================================================================================

-- ========== N5 섹터 1 (시간 관련) ==========

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-001', '日', 'ニチ', 'ジツ', NULL, 'ひ', 'か', NULL,
        '해, 날', '해, 날짜를 나타내는 한자', '日本(にほん)', '毎日(まいにち)', '日曜日(にちようび)',
        'N5', 1, 1);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-002', '月', 'ゲツ', 'ガツ', NULL, 'つき', NULL, NULL,
        '달, 월', '달, 월을 나타내는 한자', '月曜日(げつようび)', '一月(いちがつ)', '今月(こんげつ)',
        'N5', 1, 2);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-003', '火', 'カ', NULL, NULL, 'ひ', NULL, NULL,
        '불', '불을 나타내는 한자', '火曜日(かようび)', '火事(かじ)', '花火(はなび)',
        'N5', 1, 3);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-004', '水', 'スイ', NULL, NULL, 'みず', NULL, NULL,
        '물', '물을 나타내는 한자', '水曜日(すいようび)', '水(みず)', '水泳(すいえい)',
        'N5', 1, 4);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-005', '木', 'モク', 'ボク', NULL, 'き', NULL, NULL,
        '나무', '나무를 나타내는 한자', '木曜日(もくようび)', '木(き)', '木造(もくぞう)',
        'N5', 1, 5);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-006', '金', 'キン', 'コン', NULL, 'かね', 'かな', NULL,
        '쇠, 돈', '금, 쇠, 돈을 나타내는 한자', '金曜日(きんようび)', '金(かね)', '料金(りょうきん)',
        'N5', 1, 6);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-007', '土', 'ド', 'ト', NULL, 'つち', NULL, NULL,
        '흙', '흙, 토요일을 나타내는 한자', '土曜日(どようび)', '土地(とち)', '国土(こくど)',
        'N5', 1, 7);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-008', '年', 'ネン', NULL, NULL, 'とし', NULL, NULL,
        '해, 년', '년도, 해를 나타내는 한자', '今年(ことし)', '去年(きょねん)', '来年(らいねん)',
        'N5', 1, 8);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-009', '時', 'ジ', NULL, NULL, 'とき', NULL, NULL,
        '때, 시', '시간, 때를 나타내는 한자', '時間(じかん)', '何時(なんじ)', '時々(ときどき)',
        'N5', 1, 9);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-010', '分', 'フン', 'ブン', 'ブ', 'わける', 'わかれる', 'わかる',
        '나누다, 분', '나누다, 시간의 분', '分(ふん)', '十分(じゅうぶん)', '半分(はんぶん)',
        'N5', 1, 10);


-- ========== N5 섹터 2 (숫자 관련) ==========

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-011', '一', 'イチ', 'イツ', NULL, 'ひと', 'ひとつ', NULL,
        '하나', '숫자 1을 나타내는 한자', '一(いち)', '一つ(ひとつ)', '一日(ついたち)',
        'N5', 2, 1);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-012', '二', 'ニ', NULL, NULL, 'ふた', 'ふたつ', NULL,
        '둘', '숫자 2를 나타내는 한자', '二(に)', '二つ(ふたつ)', '二日(ふつか)',
        'N5', 2, 2);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-013', '三', 'サン', NULL, NULL, 'み', 'みつ', 'みっつ',
        '셋', '숫자 3을 나타내는 한자', '三(さん)', '三つ(みっつ)', '三日(みっか)',
        'N5', 2, 3);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-014', '四', 'シ', NULL, NULL, 'よ', 'よつ', 'よっつ',
        '넷', '숫자 4를 나타내는 한자', '四(し)', '四つ(よっつ)', '四日(よっか)',
        'N5', 2, 4);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-015', '五', 'ゴ', NULL, NULL, 'いつ', 'いつつ', NULL,
        '다섯', '숫자 5를 나타내는 한자', '五(ご)', '五つ(いつつ)', '五日(いつか)',
        'N5', 2, 5);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-016', '六', 'ロク', NULL, NULL, 'む', 'むつ', 'むっつ',
        '여섯', '숫자 6을 나타내는 한자', '六(ろく)', '六つ(むっつ)', '六日(むいか)',
        'N5', 2, 6);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-017', '七', 'シチ', NULL, NULL, 'なな', 'ななつ', NULL,
        '일곱', '숫자 7을 나타내는 한자', '七(しち)', '七つ(ななつ)', '七日(なのか)',
        'N5', 2, 7);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-018', '八', 'ハチ', NULL, NULL, 'や', 'やつ', 'やっつ',
        '여덟', '숫자 8을 나타내는 한자', '八(はち)', '八つ(やっつ)', '八日(ようか)',
        'N5', 2, 8);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-019', '九', 'キュウ', 'ク', NULL, 'ここの', 'ここのつ', NULL,
        '아홉', '숫자 9를 나타내는 한자', '九(きゅう)', '九つ(ここのつ)', '九日(ここのか)',
        'N5', 2, 9);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-020', '十', 'ジュウ', NULL, NULL, 'とお', 'と', NULL,
        '열', '숫자 10을 나타내는 한자', '十(じゅう)', '十日(とおか)', '二十(にじゅう)',
        'N5', 2, 10);


-- ========== N5 섹터 3 (사람/가족 관련) ==========

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-021', '人', 'ジン', 'ニン', NULL, 'ひと', NULL, NULL,
        '사람', '사람을 나타내는 한자', '人(ひと)', '日本人(にほんじん)', '三人(さんにん)',
        'N5', 3, 1);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-022', '父', 'フ', NULL, NULL, 'ちち', NULL, NULL,
        '아버지', '아버지를 나타내는 한자', '父(ちち)', '父親(ちちおや)', '祖父(そふ)',
        'N5', 3, 2);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-023', '母', 'ボ', NULL, NULL, 'はは', NULL, NULL,
        '어머니', '어머니를 나타내는 한자', '母(はは)', '母親(ははおや)', '祖母(そぼ)',
        'N5', 3, 3);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-024', '子', 'シ', 'ス', NULL, 'こ', NULL, NULL,
        '아이', '아이를 나타내는 한자', '子供(こども)', '女の子(おんなのこ)', '男の子(おとこのこ)',
        'N5', 3, 4);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-025', '男', 'ダン', 'ナン', NULL, 'おとこ', NULL, NULL,
        '남자', '남자를 나타내는 한자', '男(おとこ)', '男の子(おとこのこ)', '長男(ちょうなん)',
        'N5', 3, 5);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-026', '女', 'ジョ', 'ニョ', NULL, 'おんな', 'め', NULL,
        '여자', '여자를 나타내는 한자', '女(おんな)', '女の子(おんなのこ)', '女性(じょせい)',
        'N5', 3, 6);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-027', '友', 'ユウ', NULL, NULL, 'とも', NULL, NULL,
        '친구', '친구를 나타내는 한자', '友達(ともだち)', '友人(ゆうじん)', '親友(しんゆう)',
        'N5', 3, 7);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-028', '先', 'セン', NULL, NULL, 'さき', NULL, NULL,
        '먼저, 앞', '먼저, 선생을 나타내는 한자', '先生(せんせい)', '先週(せんしゅう)', '先月(せんげつ)',
        'N5', 3, 8);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-029', '生', 'セイ', 'ショウ', NULL, 'いきる', 'いかす', 'うまれる',
        '나다, 살다', '태어나다, 살다를 나타내는 한자', '先生(せんせい)', '学生(がくせい)', '生活(せいかつ)',
        'N5', 3, 9);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-030', '名', 'メイ', 'ミョウ', NULL, 'な', NULL, NULL,
        '이름', '이름을 나타내는 한자', '名前(なまえ)', '有名(ゆうめい)', '氏名(しめい)',
        'N5', 3, 10);


-- ========== N5 섹터 4 (장소/방향 관련) ==========

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-031', '上', 'ジョウ', NULL, NULL, 'うえ', 'あがる', 'のぼる',
        '위', '위를 나타내는 한자', '上(うえ)', '上手(じょうず)', '以上(いじょう)',
        'N5', 4, 1);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-032', '下', 'カ', 'ゲ', NULL, 'した', 'さがる', 'くだる',
        '아래', '아래를 나타내는 한자', '下(した)', '下手(へた)', '地下(ちか)',
        'N5', 4, 2);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-033', '中', 'チュウ', 'ジュウ', NULL, 'なか', NULL, NULL,
        '가운데', '가운데를 나타내는 한자', '中(なか)', '中国(ちゅうごく)', '一日中(いちにちじゅう)',
        'N5', 4, 3);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-034', '外', 'ガイ', 'ゲ', NULL, 'そと', 'はずす', 'はずれる',
        '밖', '밖을 나타내는 한자', '外(そと)', '外国(がいこく)', '意外(いがい)',
        'N5', 4, 4);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-035', '前', 'ゼン', NULL, NULL, 'まえ', NULL, NULL,
        '앞', '앞을 나타내는 한자', '前(まえ)', '午前(ごぜん)', '名前(なまえ)',
        'N5', 4, 5);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-036', '後', 'ゴ', 'コウ', NULL, 'あと', 'うしろ', 'のち',
        '뒤', '뒤를 나타내는 한자', '後(うしろ)', '午後(ごご)', '後で(あとで)',
        'N5', 4, 6);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-037', '左', 'サ', NULL, NULL, 'ひだり', NULL, NULL,
        '왼쪽', '왼쪽을 나타내는 한자', '左(ひだり)', '左側(ひだりがわ)', '左手(ひだりて)',
        'N5', 4, 7);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-038', '右', 'ウ', 'ユウ', NULL, 'みぎ', NULL, NULL,
        '오른쪽', '오른쪽을 나타내는 한자', '右(みぎ)', '右側(みぎがわ)', '右手(みぎて)',
        'N5', 4, 8);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-039', '本', 'ホン', NULL, NULL, 'もと', NULL, NULL,
        '책, 근본', '책, 근본을 나타내는 한자', '本(ほん)', '日本(にほん)', '本当(ほんとう)',
        'N5', 4, 9);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-040', '国', 'コク', NULL, NULL, 'くに', NULL, NULL,
        '나라', '나라를 나타내는 한자', '国(くに)', '外国(がいこく)', '中国(ちゅうごく)',
        'N5', 4, 10);


COMMIT;


-- ================================================================================
-- 5. 데이터 확인
-- ================================================================================

SELECT COUNT(*) AS "총 한자 수" FROM kanji;

SELECT jlpt_level, sector, COUNT(*) AS cnt
FROM kanji
GROUP BY jlpt_level, sector
ORDER BY jlpt_level, sector;

SELECT * FROM kanji ORDER BY jlpt_level, sector, index_num;



SELECT COUNT(*) FROM kanji;
SELECT COUNT(*) FROM account;

-- ================================================================================
-- 6. 출석 확인 쿼리 (kanji_log 기반)
-- ================================================================================

-- [1] 오늘 출석 여부 (accID = 1 기준)
SELECT COUNT(*) AS today_study
FROM kanji_log
WHERE accID = 1
AND TRUNC(studied_at) = TRUNC(SYSDATE);

-- [2] 이번 달 출석한 날짜 목록
SELECT DISTINCT EXTRACT(DAY FROM studied_at) AS day
FROM kanji_log
WHERE accID = 1
AND EXTRACT(YEAR FROM studied_at) = 2026
AND EXTRACT(MONTH FROM studied_at) = 2
ORDER BY day;

-- [3] 이번 달 출석 일수
SELECT COUNT(DISTINCT TRUNC(studied_at)) AS attend_days
FROM kanji_log
WHERE accID = 1
AND EXTRACT(YEAR FROM studied_at) = 2026
AND EXTRACT(MONTH FROM studied_at) = 2;


SELECT COUNT(*) FROM kanji;
SELECT COUNT(*) FROM kanji WHERE jlpt_level = 'N5';

-- ================================================================================
-- 7. 전체 테이블 확인
-- ================================================================================

SELECT * FROM account;
SELECT * FROM kanji;
SELECT * FROM kanji_log;

SELECT USER FROM dual;

-- 현재 접속 사용자 확인
SELECT USER FROM dual;

-- account 테이블이 어느 스키마에 있는지
SELECT owner, table_name FROM all_tables WHERE table_name = 'ACCOUNT';

-- kanji 테이블이 어느 스키마에 있는지  
SELECT owner, table_name FROM all_tables WHERE table_name = 'KANJI';

-- kanji_LOG 테이블이 어느 스키마에 있는지  
SELECT owner, table_name FROM all_tables WHERE table_name = 'KANJI_LOG';